Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2021-10, with the labels that each got.

#153 Fix trains embedded meshes and wrong Wheel direction
  src/Resources/Basic/Blender/Wagon_1.blend
  src/Resources/Basic/Blender/Wagon_1_WithDriverStand.blend
  src/Trains/JFR1/JFR1_Grey.tscn
  src/Trains/JFR1/JFR1_Red.tscn
  src/Trains/JFR1/Wagon_1.obj
  src/Trains/JFR1/Wagon_1_WithDriverStand.obj
Labels: bug

#144 Remove trailing whitespaces and tabs
  src/README.gd
  src/Resources/Basic/Screens/Screen1/Screen1.gd
  src/Resources/Basic/Screens/ScreenLeft/ScreenLeft.gd
  src/Resources/Basic/Screens/ScreenRight/ScreenRight.gd
  src/Resources/Basic/SignalTypes/CombinedHpVo/Form/CombinedHpVoForm.gd
  src/Resources/Basic/SignalTypes/CombinedHpVo/Light/CombinedHpVoLight.gd
  src/Resources/Basic/SignalTypes/Hl/Hl.gd
  src/Resources/Basic/SignalTypes/Ks/ScriptingKs.gd
  src/Trains/JFR1/Sound.gd
  src/Trains/JFR1/SpecificScripting.gd
  src/Trains/JFR1/SpecificScriptingGrey.gd
  src/Worlds/Signal-Tutorial/Scripting.gd
  src/Worlds/Tutorials/TutorialScript.gd
  src/addons/Libre_Train_Sim_Editor/Data/Editor/AddObjects.gd
  src/addons/Libre_Train_Sim_Editor/Data/Editor/BuildingSettings.gd
  src/addons/Libre_Train_Sim_Editor/Data/Editor/Content_Selector.gd
  src/addons/Libre_Train_Sim_Editor/Data/Editor/RailLogic.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/AdvancedEngineSound.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/BuildingsNode.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Camera.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/CustomScenarioTemplate.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/EasyEngineSound.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/EditorHUD.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Enums/PlatformSide.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Enums/reverser_state.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Forest.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Gizmo.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/HUD.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/MainMenu.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Main_Menu_Editor_Configuration.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Math.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/MobileHUD.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Person.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Rail.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/RailMap.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Root.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/StationJumper.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/TrackObjects.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/TrainInfo.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Wagon.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/WagonSound.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/World.gd
  src/addons/Libre_Train_Sim_Editor/Docks/Configuration/Configuration.gd
  src/addons/Libre_Train_Sim_Editor/Docks/Configuration/time_field.gd
  src/addons/Libre_Train_Sim_Editor/Docks/RailAttachments/MaterialSelection.gd
  src/addons/Libre_Train_Sim_Editor/Docks/RailAttachments/RailAttachments.gd
  src/addons/Libre_Train_Sim_Editor/Docks/RailBuilder/RailBuilder.gd
  src/addons/Libre_Train_Sim_Editor/plugin.gd
  src/addons/jean28518.jTools/README.gd
  src/addons/jean28518.jTools/example/example.gd
  src/addons/jean28518.jTools/jAudioManager/JAudioManager.gd
  src/addons/jean28518.jTools/jSaveManager/jSaveManager.gd
  src/addons/jean28518.jTools/jSaveManager/jSaveModule.gd
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jTable/LineControl.gd
  src/addons/jean28518.jTools/jTable/jTable.gd
Labels: enhancement

#147 Fix ProjectSettings.save() being called
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Root.gd
Labels: bug

#172 Improve editor camera
  src/addons/Libre_Train_Sim_Editor/Data/Modules/Editor.tscn
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/camera_base.gd
  src/addons/Libre_Train_Sim_Editor/Data/Scripts/editor_camera.gd
  src/project.godot
Labels: enhancement, editor

#205 Fix selection color of buttons and ItemLists
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_both.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_both_hover.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_center.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_center_hover.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_left.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_left_hover.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_right.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/button_right_hover.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/item_list.tres
  src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/styles/line_edit_focus.tres
Labels: bug, enhancement

#206 Fix tutorials not getting properly exported
  src/export_presets.cfg
Labels: bug
