Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2021-12, with the labels that each got.

#276 fix chunks not unloading correctly
  src/Data/Modules/TrackObjects.tscn
  src/Data/Scripts/Rail.gd
  src/Data/Scripts/TrackObjects.gd
  src/Data/Scripts/chunk_manager.gd
Labels: bug

#274 Fix message label readability using blur
  src/Data/Scripts/HUD.gd
  src/Data/UI/HUD.tscn
  src/Data/UI/Pause.tscn
  src/Data/UI/blur.gdshader
  src/Data/UI/blur.tres
Labels: bug, enhancement

#275 Enable MSAA x4 for JFR1 screen textures
  src/Trains/JFR1/JFR1_Grey.tscn
  src/Trains/JFR1/JFR1_Red.tscn
Labels: enhancement
