Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2021-11, with the labels that each got.

#208 Add Highlight postprocessing to Editor selection (remove bouncing animation)
  src/Data/Postprocess/HighlightPP.tscn
  src/Data/Postprocess/LaplaceEdgeDetect.gdshader
  src/Data/Postprocess/MaximumShader.gdshader
  src/Data/Postprocess/OutlinesPP.tscn
  src/Data/Postprocess/ShaderPP.gd
  src/Data/Postprocess/highlight_shader.gdshader
  src/Editor/Editor.tscn
  src/Editor/Scripts/Editor.gd
Labels: enhancement, editor

#207 Fix sounds engine sounds playing when game is paused
  src/Data/Modules/AdvancedEngineSound.tscn
  src/Data/Modules/WagonSound.tscn
  src/Data/Scripts/AdvancedEngineSound.gd
  src/Data/Scripts/WagonSound.gd
Labels: bug

#217 automatically add poles when rail is electric
  src/Data/Scripts/Rail.gd
  src/Editor/Docks/RailAttachments/RailAttachments.gd
  src/Editor/Docks/RailBuilder/RailBuilder.gd
  src/Editor/Scripts/Editor.gd
Labels: bug, editor, ux

#226 Nicer modding tools
  src/addons/libre_trainsim_modding_tools/dock.gd
  src/addons/libre_trainsim_modding_tools/dock.tscn
  src/addons/libre_trainsim_modding_tools/new_mod_popup.gd
  src/addons/libre_trainsim_modding_tools/notice_popup.gd
  src/addons/libre_trainsim_modding_tools/notice_popup.tscn
  src/addons/libre_trainsim_modding_tools/plugin.gd
  src/project.godot
Labels: enhancement

#234 fix default rail in new world has no poles
  src/Data/Modules/World-Pattern.save
Labels: bug, enhancement, editor

#235 fix everything using the wrong audio bus
  src/Data/Modules/AdvancedEngineSound.tscn
  src/Data/Modules/EasyEngineSound.tscn
  src/Data/Modules/WagonSound.tscn
  src/Data/Scripts/AdvancedEngineSound.gd
  src/Data/Scripts/EasyEngineSound.gd
  src/Data/UI/main_menu.tscn
  src/Data/default_bus_layout.tres
  src/Trains/JFR1/Sound.gd
  src/addons/jean28518.jTools/jAudioManager/JAudioManager.gd
  src/addons/jean28518.jTools/jAudioManager/jAudoManager_bus_layout.tres
Labels: enhancement, ux

#227 Add mod exporting
  src/addons/libre_trainsim_modding_tools/dock.gd
  src/addons/libre_trainsim_modding_tools/dock.tscn
Labels: enhancement, modding

#228 Convert editor maps to mods
  src/Data/Modules/SpeedLimit_Lf7.tscn
  src/Data/Scripts/Resources/mod_content.gd
  src/Data/Scripts/Singletons/Root.gd
  src/Data/Scripts/Singletons/content_loader.gd
  src/Data/Scripts/World.gd
  src/Data/UI/loading_screen.gd
  src/Editor/Docks/Configuration/Configuration.gd
  src/Editor/Editor.tscn
  src/Editor/Scripts/Editor.gd
  src/Editor/Scripts/SelectCollider.gd
  src/Editor/Scripts/editor_configuration.gd
  src/Editor/editor_configuration.tscn
  src/addons/jean28518.jTools/jList/jList.gd
Labels: bug, editor, breaks-worlds, modding

#237 Move camera faster the longer you move
  src/Editor/Scripts/editor_camera.gd
Labels: enhancement, editor, ux

#238 fix jsettings close on esc
  src/addons/jean28518.jTools/jSettings/JSettings.gd
Labels: bug

#240 Fix Ingame Editor Export
  src/Data/UI/play_menu.gd
  src/Editor/Scripts/Editor.gd
  src/addons/jean28518.jTools/jSaveManager/jSaveModule.gd
Labels: bug

#243 Fix RailLogic setting visiblity in _input
  src/Editor/Docks/Configuration/Configuration.tscn
  src/Editor/Editor.tscn
  src/Editor/Modules/RailLogic.gd
  src/Editor/Modules/RailLogic.tscn
Labels: bug, ux

#247 fix scenario to signals
  src/Data/Scripts/World.gd
Labels: bug

#248 add editor translations
  src/Translations/MainMenu.csv
Labels: bug

#250 Add difficulty settings
  src/Data/Scripts/PZBModule.gd
  src/Data/Scripts/SifaModule.gd
  src/Translations/MainMenu.csv
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jSettings/JSettings.tscn
Labels: enhancement

#246 fix getPathFromTo
  src/Data/Modules/PassengerSeat.tscn
  src/Data/Scripts/PassengerDoor.gd
  src/Data/Scripts/PassengerPathNode.gd
  src/Data/Scripts/PassengerSeat.gd
  src/Data/Scripts/Person.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Station.gd
  src/Data/Scripts/Wagon.gd
  src/Trains/JFR1/JFR1_Grey.tscn
  src/Trains/JFR1/JFR1_Red.tscn
  src/project.godot
Labels: bug

#256 fix JFR1 Normals
  src/Resources/Blender/Wagon_1_WithDriverStand.blend
  src/Trains/JFR1/Wagon_1_WithDriverStand.obj
  src/Trains/JFR1/Wagon_1_WithDriverStand.obj.import
Labels: bug, visuals

#257 Add spanish translation.
  src/Translations/Ingame.csv
  src/Translations/MainMenu.csv
  src/authors.tres
  src/project.godot
Labels: enhancement, translation

#259 Update project to 3.4
  .github/workflows/export.yml
  src/Data/Modules/ContactPoint.tscn
  src/Data/Modules/Hektometertafel.tscn
  src/Data/Modules/PassengerDoor.tscn
  src/Data/Modules/PassengerPathNode.tscn
  src/Data/Modules/Rail.tscn
  src/Data/Modules/Signal.tscn
  src/Data/Modules/SpeedLimit_Lf7.tscn
  src/Data/Modules/Station.tscn
  src/Data/Modules/TrackObjects.tscn
  src/Data/Modules/WarnSpeedLimit_Lf6.tscn
  src/Data/Modules/WarnSpeedLimit_Lf6small.tscn
  src/Data/Modules/WarnSpeedLimit_Zs3v.tscn
  src/Data/Modules/WarnSpeedLimit_Zs3v_small.tscn
  src/Data/Screens/ScreenMultiFunctionDisplay/screen_mfd.tscn
  src/Data/Screens/ScreenSpeedometer/screen_speedometer.tscn
  src/Data/UI/AboutAuthorLabel.tscn
  src/Data/UI/AboutLanguageLabel.tscn
  src/Data/UI/Content.tscn
  src/Data/UI/about.tscn
  src/Data/UI/loading_screen.tscn
  src/Data/UI/main_menu.tscn
  src/Data/UI/play_menu.tscn
  src/Data/UI/station_jumper.tscn
  src/Editor/Docks/Configuration/TimeField.tscn
  src/Editor/Modules/Gizmo.tscn
  src/Editor/editor_configuration.tscn
  src/Trains/JFR1/JFR1_Red.tscn
  src/addons/jean28518.jTools/example/example.tscn
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jSettings/JSettings.tscn
  src/addons/jean28518.jTools/jTable/LineControl.tscn
  src/addons/jean28518.jTools/jTable/jTable.tscn
  src/export_presets.cfg
  src/project.godot
Labels: enhancement

#249 Add very simple scoring system
  src/Data/Scripts/HUD.gd
  src/Data/Scripts/Player.gd
  src/Translations/Ingame.csv
Labels: enhancement

#264 Fix screenshots not being loaded in builds
  src/Data/UI/play_menu.gd
Labels: bug

#263 Fix Shadow Acne
  src/Data/Modules/Forest.tscn
  src/Data/Modules/TrackObjects.tscn
  src/Resources/Environments/BasicSun.tscn
  src/Resources/Environments/BasicWorldEnvironment.tres
  src/Resources/Materials/EasyTree.tres
  src/Trains/JFR1/JFR1_Grey.tscn
  src/Trains/JFR1/JFR1_Red.tscn
  src/addons/HaSa1002.light-tools/LICENSE
  src/addons/HaSa1002.light-tools/Light.png
  src/addons/HaSa1002.light-tools/Light.png.import
  src/addons/HaSa1002.light-tools/LightColor.gd
  src/addons/HaSa1002.light-tools/LightColorEditor.gd
  src/addons/HaSa1002.light-tools/LightTools.gd
  src/addons/HaSa1002.light-tools/ToolIcon.svg
  src/addons/HaSa1002.light-tools/ToolIcon.svg.import
  src/addons/HaSa1002.light-tools/plugin.cfg
  src/addons/jean28518.jTools/jList/jList.gd
  src/project.godot
Labels: bug, visuals

#262 Refactor Chunk System
  src/Data/Screens/ScreenSpeedometer/screen_pzb.gd
  src/Data/Scripts/Camera.gd
  src/Data/Scripts/Forest.gd
  src/Data/Scripts/Person.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Rail.gd
  src/Data/Scripts/RailMap.gd
  src/Data/Scripts/Singletons/Root.gd
  src/Data/Scripts/Singletons/logger.gd
  src/Data/Scripts/TrackObjects.gd
  src/Data/Scripts/World.gd
  src/Data/Scripts/camera_base.gd
  src/Data/Scripts/chunk_manager.gd
  src/Data/Scripts/rail_logic_base.gd
  src/Data/Scripts/world_object.gd
  src/Editor/Docks/Configuration/Configuration.gd
  src/Editor/Scripts/Editor.gd
  src/Translations/MainMenu.csv
  src/addons/jean28518.jTools/jSaveManager/jSaveModule.gd
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jSettings/JSettings.tscn
  src/project.godot
Labels: bug, enhancement, chunks

#266 Fix a few bugs
  src/Data/Scripts/Singletons/Root.gd
  src/Data/Scripts/aabb_to_collider.gd
  src/Editor/Docks/RailAttachments/RailAttachments.gd
  src/Editor/Modules/Content_Selector.gd
  src/Editor/Modules/RailLogic.gd
  src/Editor/Modules/RailLogic.tscn
  src/Editor/Modules/SelectCollider.tscn
  src/Editor/Scripts/Editor.gd
  src/Editor/Scripts/SelectCollider.gd
  src/Resources/SignalTypes/CombinedHpVo/Form/CombinedHpVoForm.gd
  src/Resources/SignalTypes/CombinedHpVo/Light/CombinedHpVoLight.tscn
  src/Resources/SignalTypes/Hl/Hl.tscn
  src/Resources/SignalTypes/Hp/Form/HpForm.tscn
  src/Resources/SignalTypes/Hp/Form/ScriptingHpForm.gd
  src/Resources/SignalTypes/Hp/Light/HpLight.tscn
  src/Resources/SignalTypes/Ks/Ks.tscn
  src/Resources/SignalTypes/Vo/Form/ScriptingVoForm.gd
  src/Resources/SignalTypes/Vo/Form/VoForm.tscn
  src/Resources/SignalTypes/Vo/Light/VoLight.tscn
  src/project.godot
Labels: bug
