Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2022-01, with the labels that each got.

#295 Improe cabin inside camera script
  src/Data/Scripts/Player.gd
Labels: bug

#296 Add bulgarian translation
  src/Trains/JFR1/JFR1.csv
  src/Trains/JFR1/JFR1.csv.import
  src/Translations/Ingame.csv
  src/Translations/MainMenu.csv
  src/authors.tres
  src/project.godot
Labels: translation

#316 Fix chunk manager at loading far away from world origin
  src/Data/Scripts/World.gd
  src/Data/Scripts/chunk_manager.gd
Labels: bug

#321 Fix Hl signal stack overflow
  src/Data/Scripts/Signal.gd
Labels: bug, editor, crash

#320 Fix translations not getting applied
  src/Data/UI/loading_screen.tscn
  src/Data/UI/main_menu.tscn
  src/Data/UI/play_menu.tscn
  src/Data/UI/station_jumper.tscn
  src/Data/UI/text_box.tscn
  src/Data/UI/translated_rich_rext_label.gd
  src/Editor/Modules/scenario_editor_selection.tscn
  src/Editor/editor_configuration.tscn
  src/project.godot
Labels: bug, enhancement, translation

#322 Update CI to 3.4.2
  .github/workflows/export.yml
Labels: enhancement

#323 Updated the Bulgarian and English translations
  src/Translations/MainMenu.csv
Labels: translation

#318 Fix message not getting shown when pressing back in pause menu
  src/Data/UI/pause.gd
Labels: bug

#317 Fix editor camera not grabbing keyboard focus
  src/Editor/Editor.tscn
  src/Editor/Scripts/editor_camera.gd
Labels: bug, editor

#319 Remove content import feature
  src/Data/UI/Content.gd
  src/Data/UI/Content.tscn
Labels: bug

#311 Fix german translations
  src/Translations/Ingame.csv
  src/Translations/MainMenu.csv
Labels: bug, translation
