Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2022-04, with the labels that each got.

#351 Fix wrong launch language
  src/Data/UI/main_menu.gd
Labels: bug, translation, ux

#349 Minor improvements to German translation
  src/Translations/German-Safety-Tutorials.csv
  src/Translations/Ingame.csv
  src/Translations/MainMenu.csv
  src/Translations/Tutorials.csv
Labels: translation

#353 Make text_box use the new theme
  src/Data/UI/text_box.gd
  src/Data/UI/text_box.tscn
  src/authors.tres
Labels: enhancement, visuals

#354 Add a VSync toggle to settings
  src/Data/Scripts/Station.gd
  src/Data/Scripts/Wagon.gd
  src/Data/Scripts/World.gd
  src/Data/Scripts/chunk_manager.gd
  src/Translations/MainMenu.csv
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jSettings/JSettings.tscn
  src/project.godot
Labels: enhancement

#357 Add short installation description
  README.md
Labels: enhancement
