Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2022-11, with the labels that each got.

#423 Make whole rail selectable
  src/Data/Modules/Rail.tscn
  src/Data/Scripts/Rail.gd
Labels: editor, ux

#432 Fix various bugs
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Rail.gd
  src/Data/Scripts/Resources/scenario_route.gd
  src/Data/Scripts/World.gd
  src/Resources/SignalTypes/Ks/ScriptingKs.gd
  src/Trains/JFR1/JFR1_Grey.tscn
Labels: bug

#434 Fix descriptions not being displayed
  src/Data/Scripts/World.gd
Labels: bug

#433 Convert the remaining assets
  src/Resources/Objects/decorative/bench.tscn
  src/Resources/Objects/decorative/bin.tscn
  src/Resources/Objects/decorative/factory.tscn
  src/Resources/Objects/decorative/lamp_1.tscn
  src/Resources/Objects/decorative/lamp_2.tscn
  src/Resources/Objects/decorative/transmission_tower.tscn
  src/Resources/Objects/groups/houses.tres
  src/Resources/Objects/groups/misc.tres
  src/Resources/Objects/groups/train_stations.tres
  src/Resources/Objects/houses/house_1.tscn
  src/Resources/Objects/houses/house_2.tscn
  src/Resources/Objects/houses/house_3.tscn
  src/Resources/Objects/houses/house_4.tscn
  src/Resources/Objects/houses/house_6.tscn
  src/Resources/Objects/houses/house_7.tscn
  src/Resources/Objects/train_stations/train_station_building_1.tscn
  src/Resources/Objects/train_stations/train_station_building_2.tscn
  src/Resources/Objects/train_stations/train_station_building_3.tscn
  src/Resources/Objects/train_stations/train_station_building_4.tscn
Labels: enhancement, editor, art

#436 Fix end - end rail connector
  src/Editor/Scripts/Editor.gd
Labels: bug
