Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2022-02, with the labels that each got.

#332 Fix them passenger system
  src/Data/Scripts/Person.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Rail.gd
  src/Data/Scripts/Station.gd
  src/Data/Scripts/Wagon.gd
  src/Data/Scripts/World.gd
  src/Data/Scripts/chunk_manager.gd
  src/addons/zylann.debug_draw/LICENSE.md
  src/addons/zylann.debug_draw/debug_draw.gd
  src/project.godot
Labels: bug

#267 Add new logo
  LibreTrainSimBanner-1To2.jpg
  LibreTrainSimForItch.jpg
  LibreTrainSimLogo.png
  LibreTrainSimLogo_Quad.png
  LibreTrainSimLogo_Round.png
  README.md
  src/Data/UI/blur_less.tres
  src/Data/UI/main_menu.tscn
  src/LibreTrainSimLogo_Quad.png
  src/LibreTrainSimLogo_Quad_128.png
  src/misc/banner/lts_banner_both.png
  src/misc/banner/lts_banner_both.png.import
  src/misc/banner/lts_banner_name.png
  src/misc/banner/lts_banner_name.png.import
  src/misc/banner/lts_banner_version.png
  src/misc/banner/lts_banner_version.png.import
  src/misc/logos/lts_logo_128.png
  src/misc/logos/lts_logo_128.png.import
  src/misc/logos/lts_logo_16.png
  src/misc/logos/lts_logo_16.png.import
  src/misc/logos/lts_logo_256.png
  src/misc/logos/lts_logo_256.png.import
  src/misc/logos/lts_logo_32.png
  src/misc/logos/lts_logo_32.png.import
  src/misc/logos/lts_logo_512.png
  src/misc/logos/lts_logo_512.png.import
  src/misc/logos/lts_logo_64.png
  src/misc/logos/lts_logo_64.png.import
  src/project.godot
Labels: enhancement, ux, visuals

#341 Add Debug UI (FPS Counter)
  README.md
  src/Data/Misc/banner/lts_banner_both.png
  src/Data/Misc/banner/lts_banner_both.png.import
  src/Data/Misc/banner/lts_banner_name.png
  src/Data/Misc/banner/lts_banner_name.png.import
  src/Data/Misc/banner/lts_banner_version.png
  src/Data/Misc/banner/lts_banner_version.png.import
  src/Data/Misc/logos/lts_logo_128.png
  src/Data/Misc/logos/lts_logo_128.png.import
  src/Data/Misc/logos/lts_logo_16.png
  src/Data/Misc/logos/lts_logo_16.png.import
  src/Data/Misc/logos/lts_logo_256.png
  src/Data/Misc/logos/lts_logo_256.png.import
  src/Data/Misc/logos/lts_logo_32.png
  src/Data/Misc/logos/lts_logo_32.png.import
  src/Data/Misc/logos/lts_logo_512.png
  src/Data/Misc/logos/lts_logo_512.png.import
  src/Data/Misc/logos/lts_logo_64.png
  src/Data/Misc/logos/lts_logo_64.png.import
  src/Data/UI/debug_ui.gd
  src/Data/UI/debug_ui.tscn
  src/Data/UI/main_menu.tscn
  src/project.godot
Labels: enhancement, ux
