Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2022-08, with the labels that each got.

#381 Refactor configuration into window
  src/Editor/Docks/Configuration/Configuration.gd
  src/Editor/Docks/Configuration/Configuration.tscn
  src/Editor/Docks/RailBuilder/RailBuilder.gd
  src/Editor/Editor.tscn
  src/Editor/Scripts/Editor.gd
  src/Editor/Scripts/EditorHUD.gd
  src/Editor/Scripts/pause_menu.gd
  src/project.godot
Labels: enhancement, editor, ux, code-quality

#383 Update to Godot v3.5
  .github/workflows/export.yml
  src/Data/Modules/Forest.tscn
  src/Data/Modules/Rail.tscn
  src/Data/Modules/Signal.tscn
  src/Data/Modules/Station.tscn
  src/Data/Postprocess/HighlightPP.tscn
  src/Data/Postprocess/OutlinesPP.tscn
  src/Data/Screens/ScreenReverser/screen_reverser.tscn
  src/Data/Scripts/Camera.gd
  src/Data/Scripts/Player.gd
  src/Data/UI/Content.tscn
  src/Data/UI/HUD.tscn
  src/Data/UI/Map.tscn
  src/Data/UI/Pause.tscn
  src/Data/UI/about.tscn
  src/Data/UI/custom_item_list.tscn
  src/Data/UI/loading_screen.tscn
  src/Data/UI/play_menu.tscn
  src/Data/UI/station_jumper.tscn
  src/Data/UI/styles/complete_menu.tres
  src/Data/UI/styles/item_list.tres
  src/Data/UI/styles/label_list_even.tres
  src/Data/UI/styles/label_list_odd.tres
  src/Editor/Docks/RailAttachments/RailAttachments.tscn
  src/Editor/Docks/RailBuilder/RailBuilder.tscn
  src/Editor/Modules/Content_Selector.tscn
  src/Editor/Modules/Gizmo.tscn
  src/Editor/Modules/RailLogic.tscn
  src/Editor/Modules/TimeField.tscn
  src/Editor/Modules/building_settings.tscn
  src/Editor/Modules/scenario_configuration.tscn
  src/Editor/Modules/scenario_editor_selection.tscn
  src/Editor/editor_configuration.tscn
  src/Resources/RailTypes/Invisible.tscn
  src/Resources/SignalTypes/CombinedHpVo/Light/CombinedHpVoLight.tscn
  src/Resources/SignalTypes/Hl/Hl.tscn
  src/Resources/SignalTypes/Hp/Form/HpForm.tscn
  src/Resources/SignalTypes/Hp/Light/HpLight.tscn
  src/Resources/SignalTypes/Ks/Ks.tscn
  src/Resources/SignalTypes/Vo/Form/VoForm.tscn
  src/Resources/SignalTypes/Vo/Light/VoLight.tscn
  src/Trains/JFR1/JFR1_Grey.tscn
  src/Trains/JFR1/JFR1_Red.tscn
  src/addons/HaSa1002.light-tools/LightColor.gd
  src/addons/HaSa1002.light-tools/LightColorEditor.gd
  src/addons/jean28518.jTools/example/example.tscn
  src/addons/jean28518.jTools/jList/jList.tscn
  src/addons/jean28518.jTools/jSettings/JSettings.tscn
  src/addons/jean28518.jTools/jTable/LineControl.tscn
  src/addons/jean28518.jTools/jTable/jTable.tscn
  src/addons/libre_trainsim_modding_tools/dock.tscn
Labels: enhancement

#380 Add FPS Limiter to Settings (requires Godot 3.5)
  src/Translations/MainMenu.csv
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jSettings/JSettings.tscn
Labels: enhancement

#277 Use Radians for Calculations
  src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
  src/Data/Scripts/AdvancedEngineSound.gd
  src/Data/Scripts/Camera.gd
  src/Data/Scripts/ContactPoint.gd
  src/Data/Scripts/EasyEngineSound.gd
  src/Data/Scripts/HUD.gd
  src/Data/Scripts/PZBMagnet.gd
  src/Data/Scripts/PZBModule.gd
  src/Data/Scripts/PZB_Debug_Monitor.gd
  src/Data/Scripts/Person.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Rail.gd
  src/Data/Scripts/RailMap.gd
  src/Data/Scripts/RailType.gd
  src/Data/Scripts/SifaModule.gd
  src/Data/Scripts/Signal.gd
  src/Data/Scripts/Singletons/Math.gd
  src/Data/Scripts/SpeedLimitSignal.gd
  src/Data/Scripts/SpeedLimitWarnSignal.gd
  src/Data/Scripts/Station.gd
  src/Data/Scripts/TrackObjects.gd
  src/Data/Scripts/Wagon.gd
  src/Data/Scripts/WagonSound.gd
  src/Data/Scripts/World.gd
  src/Editor/Docks/RailAttachments/RailAttachments.gd
  src/Editor/Docks/RailBuilder/RailBuilder.gd
  src/Editor/Modules/time_field.gd
  src/Editor/Scripts/Editor.gd
  src/Editor/Scripts/EditorHUD.gd
  src/Editor/Scripts/Gizmo.gd
  src/Editor/Scripts/scenario_map.gd
  src/Trains/JFR1/Sound.gd
  src/Trains/JFR1/SpecificScripting.gd
  src/Trains/JFR1/SpecificScriptingGrey.gd
  src/Worlds/German-Safety-Tutorials/German-Safety-Tutorials.save
  src/Worlds/German-Safety-Tutorials/German-Safety-Tutorials.tscn
  src/Worlds/German-Safety-Tutorials/SafetyTutorialScript.gd
  src/Worlds/Signal-Tutorial/Signal-Tutorial.save
  src/Worlds/Signal-Tutorial/Signal-Tutorial.tscn
  src/Worlds/Tutorials/TutorialScript.gd
  src/Worlds/Tutorials/Tutorials.save
  src/Worlds/Tutorials/Tutorials.tscn
Labels: enhancement, code-quality

#386 fix FreeCamera sensitivity
  src/Data/Scripts/Camera.gd
Labels: bug

#389 fix scenario editor
  src/Editor/Modules/Rail2DCollider.gd
  src/Editor/Scripts/scenario_map.gd
Labels: bug, editor, crash

#396 fix angle_distance_rad
  src/Data/Scripts/Singletons/Math.gd
Labels: bug, cherrypick:0.9

#393 Fix: incorrect conversion to radians
  src/Data/Scripts/Rail.gd
  src/Editor/Docks/RailBuilder/RailBuilder.gd
Labels: bug

#397 cherry-pick #394 for 0.9
  src/addons/libre_trainsim_modding_tools/dock.gd
Labels: bug, modding

#398 cherry-pick #396 for v0.9
  src/Data/Scripts/Singletons/Math.gd
Labels: bug

#394 fix mod export missing textures and meshes
  src/addons/libre_trainsim_modding_tools/dock.gd
Labels: bug, modding
