Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2023-01, with the labels that each got.

#454 Remove old route baking
  src/Data/Scripts/ContactPoint.gd
  src/Data/Scripts/PZBMagnet.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/RailMap.gd
  src/Data/Scripts/Resources/route_point.gd
  src/Data/Scripts/Resources/route_point_despawn.gd
  src/Data/Scripts/Resources/route_point_spawn.gd
  src/Data/Scripts/Resources/route_point_station.gd
  src/Data/Scripts/Resources/route_point_waypoint.gd
  src/Data/Scripts/Resources/scenario_route.gd
  src/Data/Scripts/Signal.gd
  src/Data/Scripts/SpeedLimitSignal.gd
  src/Data/Scripts/SpeedLimitWarnSignal.gd
  src/Data/Scripts/Station.gd
  src/Data/Scripts/Wagon.gd
  src/Data/Scripts/World.gd
  src/Data/Scripts/chunk_manager.gd
  src/Data/Scripts/rail_logic_base.gd
  src/Data/Scripts/train_spawn_information.gd
  src/Editor/Modules/scenario_configuration.tscn
  src/Editor/Modules/scenario_editor.tscn
  src/Editor/Scripts/ScenarioConfiguration.gd
  src/Editor/Scripts/scenario_editor.gd
  src/Editor/Scripts/scenario_map.gd
  src/Worlds/German-Safety-Tutorials/German-Safety-Tutorials.tscn
Labels: bug

#451 Fix track objects not updating their position on world origin shift
  src/Data/Scripts/TrackObjects.gd
Labels: bug, chunks

#457 Auto Hide Zs3/Zs3v on Ks-Signals
  src/Resources/SignalTypes/Ks/KS-Sig.obj
  src/Resources/SignalTypes/Ks/Ks.tscn
  src/Resources/SignalTypes/Ks/ScriptingKs.gd
  src/Resources/SignalTypes/Ks/Zs3.obj
  src/Resources/SignalTypes/Ks/Zs3v.obj
Labels: bug, art

#458 Add Zs3/Zs3v import files
  src/Resources/SignalTypes/Ks/Zs3.obj.import
  src/Resources/SignalTypes/Ks/Zs3v.obj.import
Labels: bug

#466 Properly format markdown
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: Priority:Low, code-quality
