Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2023-12, with the labels that each got.

#546 remove speed limit indicator
  src/Data/Screens/ScreenSpeedometer/SpeedLimit.png
  src/Data/Screens/ScreenSpeedometer/SpeedLimit.png.import
  src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
  src/Data/Screens/ScreenSpeedometer/screen_speedometer.tscn
Labels: visuals, design

#549 Add render stats to debug window
  src/Data/UI/debug_ui.gd
  src/Data/UI/debug_ui.tscn
  src/project.godot
Labels: enhancement, ¯\_(ツ)_/¯, performance

#550 Some gizmo improvements
  src/Editor/Editor.tscn
  src/Editor/Scripts/Editor.gd
  src/Editor/Scripts/EditorHUD.gd
  src/Editor/Scripts/Gizmo.gd
  src/Editor/ui/object_transform.gd
  src/project.godot
Labels: bug, enhancement, editor, ux
