Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2023-03, with the labels that each got.

#485 Add PassengerCameras to JFR1_Grey
  src/Data/Modules/FreeCamera.tscn
  src/Data/Scripts/Camera.gd
  src/Data/Scripts/Player.gd
  src/Trains/JFR1/JFR1_Grey.tscn
Labels: bug

#481 UI keyboard and controller navigation
  src/Data/Scripts/HUD.gd
  src/Data/Scripts/StationJumper.gd
  src/Data/UI/Content.gd
  src/Data/UI/Content.tscn
  src/Data/UI/about.tscn
  src/Data/UI/main_menu.gd
  src/Data/UI/menu_about.gd
  src/Data/UI/pause.gd
  src/Data/UI/play_menu.gd
  src/Data/UI/styles/button_both_focus.tres
  src/Data/UI/styles/button_center_focus.tres
  src/Data/UI/styles/button_left_focus.tres
  src/Data/UI/styles/button_right_focused.tres
  src/Data/UI/styles/complete_menu.tres
  src/Data/UI/text_box.gd
  src/Data/UI/text_box.tscn
  src/Editor/Modules/scenario_editor_selection.tscn
  src/Editor/Scripts/EditorHUD.gd
  src/Editor/Scripts/editor_configuration.gd
  src/Editor/Scripts/pause_menu.gd
  src/Editor/Scripts/scenario_editor.gd
  src/Editor/Scripts/scenario_editor_selection.gd
  src/addons/jean28518.jTools/jList/jList.gd
  src/addons/jean28518.jTools/jList/jList.tscn
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/addons/jean28518.jTools/jSettings/input_presets/layout_lts.tres
  src/addons/jean28518.jTools/jSettings/input_presets/layout_openbve.tres
  src/addons/jean28518.jTools/jSettings/input_settings.tscn
  src/project.godot
Labels: enhancement, ux

#492 Fix build version not having enough data to create version
  .github/workflows/export.yml
Labels: bug, CI

#494 Fix message text changed when opening settings
  src/Data/UI/text_box.gd
  src/Data/UI/translated_rich_rext_label.gd
Labels: bug, ux

#491 Fix excessive VRAM use of signals and speed limit signs
  src/Data/Modules/Hektometertafel.tscn
  src/Data/Modules/SpeedLimit_Lf7.tscn
  src/Data/Modules/SpeedLimit_Zs3.tscn
  src/Data/Modules/SpeedLimit_Zs3_small.tscn
  src/Data/Modules/WarnSpeedLimit_Lf6.tscn
  src/Data/Modules/WarnSpeedLimit_Lf6small.tscn
  src/Data/Modules/WarnSpeedLimit_Zs3v.tscn
  src/Data/Modules/WarnSpeedLimit_Zs3v_small.tscn
  src/Data/Scripts/Hektometertafel.gd
  src/Data/Scripts/SpeedLimitSignal.gd
  src/Data/Scripts/SpeedLimitWarnSignal.gd
  src/Resources/Blender/lf7.blend
  src/Resources/Blender/zs3.blend
  src/Resources/Blender/zs3_small.blend
  src/Resources/Objects/lf7.obj
  src/Resources/Objects/zs3.obj
  src/Resources/Objects/zs3_small.obj
  src/Resources/SignalTypes/Ks/Ks.tscn
  src/Resources/SignalTypes/Ks/ScriptingKs.gd
Labels: performance

#487 Add generic pull request template
  .github/PULL_REQUEST_TEMPLATE/generic_pull_request.md
Labels: enhancement

#496 prevent PZBMagnet error message
  src/Data/Scripts/Player.gd
  src/addons/jean28518.jTools/jSettings/input_presets/layout_lts.tres
  src/addons/jean28518.jTools/jSettings/input_presets/layout_openbve.tres
Labels: code-quality

#498 Localize input settings
  src/Translations/MainMenu.csv
  src/addons/jean28518.jTools/jSettings/input_settings.gd
Labels: translation, ux

#507 Optimise Pathfinding
  src/Data/Scripts/Rail.gd
  src/Data/Scripts/Resources/scenario_route.gd
  src/Data/Scripts/World.gd
  src/Editor/Scripts/scenario_map.gd
  src/project.godot
Labels: bug, editor, crash, performance

#501 Version Exporter: Ignore MacOS Key Modifications
  .github/workflows/project.godot.ignores
  src/addons/hasa1002.buildversion/version_exporter.gd
  src/project.godot
Labels: bug, CI, w4godot
