Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2023-02, with the labels that each got.

#459 Fix speed limits not updating their sign
  src/Data/Modules/SpeedLimit_Lf7.tscn
  src/Data/Scripts/SpeedLimitSignal.gd
Labels: bug

#453 Fix tutorial scripts
  src/Worlds/Tutorials/TutorialScript.gd
  src/Worlds/Tutorials/Tutorials.tscn
Labels: bug

#463 Fix loader crashing if loading count is wrong
  src/Data/UI/loading_screen.gd
Labels: bug, crash

#470 Prioritize emergency braking over restrictive mode
  src/Data/Scripts/PZBModule.gd
Labels: bug

#452 Fix grass and chunk not agreeing on the correct coordinate system to use
  src/Data/Scripts/chunk_loader_interactive.gd
  src/Data/Scripts/chunk_manager.gd
  src/Editor/Scripts/Editor.gd
  src/project.godot
Labels: bug, breaks-worlds, chunks

#467 Add CI-able build version
  .github/workflows/export.yml
  src/Data/UI/main_menu.gd
  src/Data/UI/main_menu.tscn
  src/addons/hasa1002.buildversion/LICENSE
  src/addons/hasa1002.buildversion/plugin.cfg
  src/addons/hasa1002.buildversion/plugin.gd
  src/addons/hasa1002.buildversion/version_exporter.gd
  src/addons/jean28518.jTools/jSettings/JSettings.gd
  src/project.godot
Labels: enhancement

#455 Fix pause behaviour
  src/Data/Scripts/Camera.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Singletons/Root.gd
  src/Data/UI/HUD.tscn
  src/Data/UI/loading_screen.gd
  src/Data/UI/pause.gd
  src/Data/UI/text_box.gd
Labels: bug, ux

#475 Multiple controller icon fixes
  src/Data/Fonts/image_offset_pseudo_medium.tres
  src/Data/Scripts/HUD.gd
  src/Data/UI/HUD.tscn
  src/Data/UI/input_rich_text_label.gd
  src/addons/controller_icons/ControllerIcons.gd
  src/addons/controller_icons/Mapper.gd
  src/addons/controller_icons/Settings.gd
  src/addons/controller_icons/objects/Button.gd
  src/addons/controller_icons/objects/Sprite.gd
  src/addons/controller_icons/objects/Sprite3D.gd
  src/addons/controller_icons/objects/TextureRect.gd
  src/project.godot
Labels: bug

#462 Convert built-in worlds to 1000m chunks
  src/Worlds/German-Safety-Tutorials/German-Safety-Tutorials-scenarios.cfg
  src/Worlds/German-Safety-Tutorials/German-Safety-Tutorials.tscn
  src/Worlds/German-Safety-Tutorials/chunks/chunk_0_0.tscn
  src/Worlds/German-Safety-Tutorials/chunks/chunk_1_0.tscn
  src/Worlds/German-Safety-Tutorials/chunks/chunk_2_0.tscn
  src/Worlds/German-Safety-Tutorials/chunks/chunk_3_0.tscn
  src/Worlds/Signal-Tutorial/Signal-Tutorial-scenarios.cfg
  src/Worlds/Signal-Tutorial/Signal-Tutorial.tscn
  src/Worlds/Signal-Tutorial/chunks/chunk_0_0.tscn
  src/Worlds/Signal-Tutorial/chunks/chunk_1_0.tscn
  src/Worlds/Tutorials/Tutorials.tscn
  src/Worlds/Tutorials/chunks/chunk_0_0.tscn
  src/Worlds/Tutorials/chunks/chunk_1_0.tscn
Labels: bug, breaks-worlds, chunks

#478 Fix: Restart scenario while message open
  src/Data/UI/pause.gd
Labels: bug

#476 Rail debugging tools
  src/Data/Scripts/Rail.gd
  src/Data/UI/custom_item_list.gd
  src/Editor/Docks/RailBuilder/RailBuilder.gd
  src/Editor/Docks/RailBuilder/RailBuilder.tscn
  src/project.godot
Labels: bug, enhancement, editor

#489 Fix train selection
  src/Data/Scripts/World.gd
Labels: bug
