Repository Libre-TrainSim/Libre-TrainSim, pull requests merged in 2023-08, with the labels that each got.

#522 Fixes passengers walking through closing doors
  src/Data/Scripts/Person.gd
Labels: bug

#524 Fix get_chunks to properly return surrounding chunks
  src/Data/Scripts/chunk_manager.gd
Labels: bug, chunks

#519 Editor gizmo upgrade
  src/Editor/Editor.tscn
  src/Editor/Modules/Gizmo.tscn
  src/Editor/Modules/gizmo_rot_collider.tres
  src/Editor/Scripts/EditorHUD.gd
  src/Editor/Scripts/Gizmo.gd
  src/Resources/Objects/RotationGizmo.obj
  src/Resources/Objects/RotationGizmo.obj.import
  src/project.godot
Labels: enhancement, editor

#528 Door states and Person navigation improvements
  src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
  src/Data/Scripts/CustomScenarioTemplate.gd
  src/Data/Scripts/Enums/door_state.gd
  src/Data/Scripts/HUD.gd
  src/Data/Scripts/PassengerDoor.gd
  src/Data/Scripts/Person.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/TrainInfo.gd
  src/Data/Scripts/Wagon.gd
  src/Trains/JFR1/JFR1_Grey.tscn
  src/Trains/JFR1/JFR1_Red.tscn
  src/Trains/JFR1/SpecificScripting.gd
  src/Trains/JFR1/SpecificScriptingGrey.gd
  src/Worlds/Tutorials/TutorialScript.gd
  src/project.godot
Labels: enhancement

#533 Unselect previously selected list item to allow reselection
  src/Editor/Modules/add_objects.gd
Labels: enhancement, editor, ux

#529 Persons FSM and navigation update
  src/Data/Scripts/Camera.gd
  src/Data/Scripts/Enums/door_state.gd
  src/Data/Scripts/Person.gd
  src/Data/Scripts/Player.gd
  src/Data/Scripts/Station.gd
  src/Data/Scripts/Wagon.gd
  src/Data/Scripts/World.gd
  src/Data/UI/debug_ui.gd
  src/Data/UI/debug_ui.tscn
  src/addons/basil.debug_labels/debug_label.gd
  src/addons/basil.debug_labels/plugin.cfg
  src/project.godot
Labels: bug, enhancement

#535 Fix Scenario Editor route renaming
  src/Editor/Scripts/ScenarioConfiguration.gd
Labels: bug
